name: build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - run: dotnet clean Icod.Patch.sln -c Release
      - run: dotnet restore Icod.Patch.sln
      - run: dotnet build Icod.Patch.sln -c Release --no-restore -p:ContinuousIntegrationBuild=true
